import "./style.css";
import { protectGlossary, restoreGlossary } from "./glossary";
import { clearOpenAiApiKey, getStoredOpenAiApiKey, getTranslationServiceStatus, saveOpenAiApiKey, translateSegment } from "./translator";

const languageModes = [
  { id: "en", label: "英文模式", recognitionLang: "en-US", targetLang: "zh-TW", targetLabel: "中文", apiMode: "english" },
  { id: "es-mx", label: "西文模式（墨西哥）", recognitionLang: "es-MX", targetLang: "zh-TW", targetLabel: "中文", apiMode: "spanish-mx" },
  { id: "es-es", label: "西文模式（西班牙）", recognitionLang: "es-ES", targetLang: "zh-TW", targetLabel: "中文", apiMode: "spanish-es" },
  { id: "de", label: "德文模式", recognitionLang: "de-DE", targetLang: "zh-TW", targetLabel: "中文", apiMode: "german" },
  { id: "ru", label: "俄文模式", recognitionLang: "ru-RU", targetLang: "zh-TW", targetLabel: "中文", apiMode: "russian" }
];
const PAUSE_MS = 1500;
const MAX_SEGMENT_LENGTH = 120;
const SEGMENT_PUNCTUATION = /[.!?。？！¿¡]$/;
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const state = { selectedModeId: languageModes[0].id, listening: false, meetingMode: false, segments: [], currentBuffer: "", sentSegments: new Set() };
let recognition; let pauseTimer; let segmentCount = 0; let stoppingIntent = false;
const app = document.querySelector("#app");
app.innerHTML = `...`;
// keep template compact by replacing afterwards
app.innerHTML = app.innerHTML.replace("...", `<header class="top-bar"><span class="version-badge">v3</span></header><button id="main-action" class="main-action">🎤 點我開始翻譯</button><section class="panel"><div id="mode-buttons" class="grid-buttons"></div></section><section class="panel"><div class="grid-buttons"><button id="meeting-mode-btn" class="feature-btn">🧠 會議模式：關</button><button id="settings-btn" class="feature-btn">⚙️ 設定</button><button id="clear-btn" class="feature-btn">🗑️ 清空</button></div></section><section class="panel"><ul class="status-list"><li>語音辨識：<span id="speech-status">待機</span></li><li>模式：<span id="mode-status">一般</span></li><li>段落數：<span id="segment-count">0</span></li><li>GPT 修正：<span id="gpt-status"></span></li><li>Google 翻譯：<span>由本站提供</span></li><li>工程術語保護：<span>已啟用</span></li></ul><p id="service-message" class="warning-text"></p></section><section class="result-grid"><article class="panel card"><h3>原文</h3><div id="source-segments" class="segment-list"><p class="hint">尚無內容</p></div></article><article class="panel card"><h3>翻譯結果</h3><div id="translated-segments" class="segment-list"><p class="hint">尚無內容</p></div></article></section><div id="settings-modal" class="modal hidden" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="modal-panel"><h3 id="settings-title">設定</h3><p class="hint">OpenAI API Key 僅儲存在你的瀏覽器，不會儲存在本站伺服器。</p><label class="settings-label" for="openai-api-key-input">OpenAI API Key</label><input id="openai-api-key-input" class="settings-input" type="password" autocomplete="off" /><div class="modal-actions"><button id="save-openai-key-btn" class="feature-btn">儲存</button><button id="clear-openai-key-btn" class="feature-btn">清除 API Key</button><button id="close-settings-btn" class="feature-btn">關閉</button></div></div></div>`);
const $ = (s) => document.querySelector(s);
const els = { main: $("#main-action"), modes: $("#mode-buttons"), meeting: $("#meeting-mode-btn"), settings: $("#settings-btn"), clear: $("#clear-btn"), speech: $("#speech-status"), mode: $("#mode-status"), count: $("#segment-count"), gpt: $("#gpt-status"), src: $("#source-segments"), dst: $("#translated-segments"), svc: $("#service-message"), modal: $("#settings-modal"), key: $("#openai-api-key-input"), save: $("#save-openai-key-btn"), clearKey: $("#clear-openai-key-btn"), close: $("#close-settings-btn") };
const mode = () => languageModes.find((m) => m.id === state.selectedModeId) ?? languageModes[0];
function render() { const st = getTranslationServiceStatus(); els.main.textContent = state.listening ? "⏹ 停止聆聽" : "🎤 點我開始翻譯"; els.gpt.textContent = st.hasOpenAiKey ? "已啟用" : "未啟用"; els.meeting.textContent = `🧠 會議模式：${state.meetingMode ? "開" : "關"}`; els.speech.textContent = state.listening ? "聆聽中" : "待機"; els.mode.textContent = state.meetingMode ? "會議" : "一般"; els.count.textContent = String(segmentCount); els.svc.textContent = st.configured ? "" : "尚未設定翻譯 API，請先部署 Cloudflare Worker"; els.modes.innerHTML = languageModes.map((m) => `<button class="mode-btn ${m.id === state.selectedModeId ? "active" : ""}" data-mode-id="${m.id}">${m.label}</button>`).join(""); if (!state.segments.length) { els.src.innerHTML = '<p class="hint">尚無內容</p>'; els.dst.innerHTML = '<p class="hint">尚無內容</p>'; return; } els.src.innerHTML = state.segments.map((s) => `<div class="segment-item"><span class="segment-index">#${s.id} · ${s.lang}</span><p>${s.sourceText}</p></div>`).join(""); els.dst.innerHTML = state.segments.map((s) => `<div class="segment-item"><span class="segment-index">#${s.id}</span><p>${s.translatedText || "Google 翻譯失敗"}</p><small>GPT 修正：${s.cleanedByGpt ? "成功" : s.gptError ? "失敗已略過" : "未啟用"}</small><br><small>Google 翻譯：${s.ok ? "成功" : "失敗"}</small><br><small>工程術語保護：已啟用</small></div>`).join(""); }
function shouldFlush(text, forceFinal=false){return forceFinal || SEGMENT_PUNCTUATION.test(text) || text.length>=MAX_SEGMENT_LENGTH;}
async function flushSegment(forceFinal=false){const raw=state.currentBuffer.trim(); if(!raw||raw.length<2)return; if(!shouldFlush(raw,forceFinal))return; state.currentBuffer=""; const normalized=raw.replace(/\s+/g," "); if(state.sentSegments.has(normalized))return; state.sentSegments.add(normalized); const {protectedText, glossaryMap}=protectGlossary(normalized); const m=mode(); const res=await translateSegment({text:normalized, protectedText, glossaryMap}, m); const cleanedRestored=restoreGlossary(res.cleanedText||protectedText, glossaryMap); const translatedRestored=restoreGlossary(res.translatedText||"", glossaryMap); const seg={id:++segmentCount, lang:m.recognitionLang, sourceText:cleanedRestored, translatedText:translatedRestored||"Google 翻譯失敗", cleanedByGpt:res.cleanedByGpt, gptError:res.gptError, ok:res.ok}; state.segments.unshift(seg); render(); if(!state.meetingMode){stopListening();}}
function resetPause(){clearTimeout(pauseTimer); pauseTimer=setTimeout(()=>{if(state.listening) flushSegment(true);},PAUSE_MS);} 
function stopListening(){stoppingIntent=true; clearTimeout(pauseTimer); if(recognition&&state.listening) recognition.stop(); state.listening=false; render();}
function startListening(){if(!SpeechRecognition){alert("此瀏覽器不支援 Web Speech API，請改用最新版 Chrome。");return;} stoppingIntent=false; recognition = new SpeechRecognition(); recognition.lang = mode().recognitionLang; recognition.interimResults = true; recognition.continuous = true; recognition.onstart=()=>{state.listening=true;render();}; recognition.onresult=(event)=>{for(let i=event.resultIndex;i<event.results.length;i+=1){const r=event.results[i]; const t=r[0].transcript.trim(); if(!t) continue; if(r.isFinal){state.currentBuffer=`${state.currentBuffer} ${t}`.trim(); flushSegment(true);} else {state.currentBuffer=`${state.currentBuffer} ${t}`.trim(); if(shouldFlush(state.currentBuffer,false)){flushSegment(false);} } resetPause(); }}; recognition.onend=()=>{state.listening=false; if(state.meetingMode && !stoppingIntent){startListening(); return;} flushSegment(true); render();}; recognition.onerror=()=>{state.listening=false; render();}; recognition.start();}
els.main.addEventListener("click", ()=> state.listening?stopListening():startListening()); els.modes.addEventListener("click",(e)=>{const t=e.target; if(!(t instanceof HTMLButtonElement)) return; const id=t.dataset.modeId; if(!id||id===state.selectedModeId)return; state.selectedModeId=id; if(state.listening){stopListening(); startListening();} render();}); els.meeting.addEventListener("click",()=>{state.meetingMode=!state.meetingMode; render();}); els.settings.addEventListener("click",()=>{els.key.value=getStoredOpenAiApiKey(); els.modal.classList.remove("hidden");}); els.close.addEventListener("click",()=>els.modal.classList.add("hidden")); els.modal.addEventListener("click",(e)=>{if(e.target===els.modal) els.modal.classList.add("hidden");}); els.save.addEventListener("click",()=>{saveOpenAiApiKey(els.key.value||""); els.modal.classList.add("hidden"); render();}); els.clearKey.addEventListener("click",()=>{clearOpenAiApiKey(); els.key.value=""; render();}); els.clear.addEventListener("click",()=>{state.segments=[];state.currentBuffer="";state.sentSegments.clear();segmentCount=0;render();});
render();
